---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: spring-petclinic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers
  namespace: spring-petclinic
  labels:
    app: customers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers
  template:
    metadata:
      labels:
        app: customers
    spec:
      containers:
        - image: spring-petclinic-customers-service:2.5.1
          imagePullPolicy: IfNotPresent
          name: customers
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: customers-service
  namespace: spring-petclinic
  labels:
    app: customers
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: customers
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits
  namespace: spring-petclinic
  labels:
    app: visits
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visits
  template:
    metadata:
      labels:
        app: visits
    spec:
      containers:
        - image: spring-petclinic-visits-service:2.5.1
          imagePullPolicy: IfNotPresent
          name: visits
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: visits-service
  namespace: spring-petclinic
  labels:
    app: visits
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: visits
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets
  namespace: spring-petclinic
  labels:
    app: vets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vets
  template:
    metadata:
      labels:
        app: vets
    spec:
      containers:
        - image: spring-petclinic-vets-service:2.5.1
          imagePullPolicy: IfNotPresent
          name: vets
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: vets-service
  namespace: spring-petclinic
  labels:
    app: vets
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: vets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: spring-petclinic
  labels:
    app: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - image: spring-petclinic-admin-server:2.5.1
          imagePullPolicy: IfNotPresent
          name: admin
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: admin
  namespace: spring-petclinic
  labels:
    app: admin
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: spring-petclinic
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - image: spring-petclinic-api-gateway:2.5.1
          imagePullPolicy: IfNotPresent
          name: gateway
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: spring-petclinic
  labels:
    app: gateway
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: gateway
